name: Backend build
on:
  push:
    paths:
      - '.github/workflows/backend.yml'
      - 'api/**'
      - '!api/.gitignore'
      - '!api/README.md'
      - '.gitmodules'
  pull_request:
    paths:
      - '.github/workflows/backend.yml'
      - 'api/**'
      - '!api/.gitignore'
      - '!api/README.md'
      - '.gitmodules'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    # - name: Build API base image
    #   id: docker-base
    #   uses: elgohr/Publish-Docker-Github-Action@master
    #   with:
    #     name: memelabs/rustla2/rustla2-api-base
    #     dockerfile: Dockerfile.base
    #     workdir: api
    #     registry: docker.pkg.github.com
    #     username: ${{ github.actor }}
    #     password: ${{ secrets.GITHUB_TOKEN }}
    # - name: Pull API base image
    #   run: docker pull docker.pkg.github.com/memelabs/rustla2/rustla2-api-base:{{ steps.docker-base.outputs.tag }}
    - name: Build API image
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: memelabs/rustla2/rustla2-api
        dockerfile: Dockerfile
        workdir: api
        registry: docker.pkg.github.com
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
